kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: ptarmiganlabs/butler-cw
    dockerfile: Dockerfile
    context: 
    # auto_tag: true
    tags:
    - latest
    - '2.1.0'
    - '2.1'
    - '2'
  when:
    event:
    - tag
