# Rename this file to production.yaml, and fill in data as needed below.

# Logging configuration
logLevel: info                    # Log level. Possible log levels are silly, debug, verbose, info, warn, error
fileLogging: false                # true/false to enable/disable logging to disk file

# Heartbeats can be used to send "I'm alive" messages to any other tool, e.g. an infrastructure monitoring tool
# The concept is simple: The remoteURL will be called at the specified frequency. The receiving tool will then know 
# that Butler CW is alive.
heartbeat:
  enabled: false
  remoteURL: http://my.monitoring.server/some/path/
  frequency: every 1 hour         # https://bunkat.github.io/later/parsers.html

# Paths to client certificates to use when connecting to Sense server. Can be pem or pvk/cer
# remove or comment out if running on desktop
clientCertPath: /path/to/client/cert/client.pem
clientCertKeyPath: /path/to/client/cert/client_key.pem
clientCertCAPath: /path/to/client/cert/root.pem
# If running in a Docker container, the cert paths MUST be the following
# clientCertPath: /nodeapp/config/certificate/client.pem
# clientCertKeyPath: /nodeapp/config/certificate/client_key.pem
# clientCertCAPath: /nodeapp/config/certificate/root.pem

# QIX version to use
qixVersion: 12.170.2

# Config on what apps should be cached
appConfig:
  # Valid options are disk, github
  configSource: disk
  
  # Leave strings empty if disk config not used
  diskConfigFile: ./config/apps.yaml

  # Leave strings empty if github not used
  github:
    host: api.github.com
    username: <username>
    password: pwd or access token
    owner: <repo owner>
    repo: <repo name, e.g. qliksense-cache-warming>
    path: config/apps.yaml

# Is connection to Sense engine secure (https)?
isSecure: true
