name: Debug MQTT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Send msg to MQTT
        uses: potaesm/github-actions-mqtt-request@1.0.0
        if: always()
        env:
          JOB_CONCLUSION: ${{ job.status }}
          NODE_VERSION: ${{ matrix.node }}
        with:
          url: ${{ secrets.PUBLIC_MQTT_BROKER_URL }}
          topic: control/github_actions_action_runner
          payload: '{ "type":"ci-test", "repo": "${{ github.repository }}", "job": "${{ github.job }}", "workflow": "${{ github.workflow }}", "nodeVersion": "${{ env.NODE_VERSION }}","status": "in_progress","conclusion":"${{ env.JOB_CONCLUSION }}" }'
          username: ${{ secrets.PUBLIC_MQTT_BROKER_USER }}
          connectTimeout: 30000
